<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 14 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord|Audiogram|VisionPrescription)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth                   CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex                 CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType                     CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse   CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute|WorkoutStatistics)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutActivity ((MetadataEntry)*)>
<!ATTLIST WorkoutActivity
  uuid                 CDATA #REQUIRED
  startDate            CDATA #REQUIRED
  endDate              CDATA #IMPLIED
  duration             CDATA #IMPLIED
  durationUnit         CDATA #IMPLIED
>
<!ELEMENT WorkoutEvent ((MetadataEntry)*)>
<!ATTLIST WorkoutEvent
  type                 CDATA #REQUIRED
  date                 CDATA #REQUIRED
  duration             CDATA #IMPLIED
  durationUnit         CDATA #IMPLIED
>
<!ELEMENT WorkoutStatistics EMPTY>
<!ATTLIST WorkoutStatistics
  type                 CDATA #REQUIRED
  startDate            CDATA #REQUIRED
  endDate              CDATA #REQUIRED
  average              CDATA #IMPLIED
  minimum              CDATA #IMPLIED
  maximum              CDATA #IMPLIED
  sum                  CDATA #IMPLIED
  unit                 CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram ((MetadataEntry|SensitivityPoint)*)>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  leftEarMasked      CDATA #IMPLIED
  leftEarClampingRangeLowerBound   CDATA #IMPLIED
  leftEarClampingRangeUpperBound   CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
  rightEarMasked      CDATA #IMPLIED
  rightEarClampingRangeLowerBound  CDATA #IMPLIED
  rightEarClampingRangeUpperBound  CDATA #IMPLIED
>
<!ELEMENT VisionPrescription ((RightEye|LeftEye|Attachment|MetadataEntry)*)>
<!ATTLIST VisionPrescription
  type             CDATA #REQUIRED
  dateIssued       CDATA #REQUIRED
  expirationDate   CDATA #IMPLIED
  brand            CDATA #IMPLIED
>
<!ELEMENT RightEye EMPTY>
<!ATTLIST RightEye
  sphere           CDATA #IMPLIED
  sphereUnit       CDATA #IMPLIED
  cylinder         CDATA #IMPLIED
  cylinderUnit     CDATA #IMPLIED
  axis             CDATA #IMPLIED
  axisUnit         CDATA #IMPLIED
  add              CDATA #IMPLIED
  addUnit          CDATA #IMPLIED
  vertex           CDATA #IMPLIED
  vertexUnit       CDATA #IMPLIED
  prismAmount      CDATA #IMPLIED
  prismAmountUnit  CDATA #IMPLIED
  prismAngle       CDATA #IMPLIED
  prismAngleUnit   CDATA #IMPLIED
  farPD            CDATA #IMPLIED
  farPDUnit        CDATA #IMPLIED
  nearPD           CDATA #IMPLIED
  nearPDUnit       CDATA #IMPLIED
  baseCurve        CDATA #IMPLIED
  baseCurveUnit    CDATA #IMPLIED
  diameter         CDATA #IMPLIED
  diameterUnit     CDATA #IMPLIED
>
<!ELEMENT LeftEye EMPTY>
<!ATTLIST LeftEye
  sphere           CDATA #IMPLIED
  sphereUnit       CDATA #IMPLIED
  cylinder         CDATA #IMPLIED
  cylinderUnit     CDATA #IMPLIED
  axis             CDATA #IMPLIED
  axisUnit         CDATA #IMPLIED
  add              CDATA #IMPLIED
  addUnit          CDATA #IMPLIED
  vertex           CDATA #IMPLIED
  vertexUnit       CDATA #IMPLIED
  prismAmount      CDATA #IMPLIED
  prismAmountUnit  CDATA #IMPLIED
  prismAngle       CDATA #IMPLIED
  prismAngleUnit   CDATA #IMPLIED
  farPD            CDATA #IMPLIED
  farPDUnit        CDATA #IMPLIED
  nearPD           CDATA #IMPLIED
  nearPDUnit       CDATA #IMPLIED
  baseCurve        CDATA #IMPLIED
  baseCurveUnit    CDATA #IMPLIED
  diameter         CDATA #IMPLIED
  diameterUnit     CDATA #IMPLIED
>
<!ELEMENT Attachment EMPTY>
<!ATTLIST Attachment
  identifier       CDATA #IMPLIED
>
]>
<HealthData locale="en_US">

<ExportDate value="2025-12-18 06:18:45 -0700" />
 

<Me HKCharacteristicTypeIdentifierDateOfBirth="1981-05-22" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="None" />
 

<Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3e40&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="ms" creationDate="2025-11-18 00:53:47 -0700" startDate="2025-11-18 00:52:46 -0700" endDate="2025-11-18 00:53:45 -0700" value="54.5307">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
  <HeartRateVariabilityMetadataList>
   <InstantaneousBeatsPerMinute bpm="60" time="12:52:48.21 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="12:52:49.19 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="12:52:50.19 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:52:51.14 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="12:52:52.08 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="12:52:53.04 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:52:53.99 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="12:52:55.02 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:52:56.05 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:52:57.09 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="12:52:58.15 AM" />
   <InstantaneousBeatsPerMinute bpm="57" time="12:52:59.21 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:00.24 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="12:53:01.31 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:02.35 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="12:53:03.34 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:04.38 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:05.42 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:06.45 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:07.49 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:08.52 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="12:53:09.52 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="12:53:10.60 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:11.63 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="12:53:12.62 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="12:53:13.60 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="12:53:14.57 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="12:53:15.55 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="12:53:16.48 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="12:53:17.48 AM" />
   <InstantaneousBeatsPerMinute bpm="66" time="12:53:18.40 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="12:53:19.34 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="12:53:20.34 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="12:53:21.27 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:53:22.22 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:23.26 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="12:53:24.27 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:53:25.23 AM" />
   <InstantaneousBeatsPerMinute bpm="66" time="12:53:26.14 AM" />
   <InstantaneousBeatsPerMinute bpm="68" time="12:53:27.02 AM" />
   <InstantaneousBeatsPerMinute bpm="65" time="12:53:27.94 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="12:53:28.95 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:29.99 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="12:53:30.96 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="12:53:31.99 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:53:32.95 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="12:53:33.85 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="12:53:34.74 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="12:53:35.64 AM" />
   <InstantaneousBeatsPerMinute bpm="68" time="12:53:36.52 AM" />
   <InstantaneousBeatsPerMinute bpm="66" time="12:53:37.42 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="12:53:38.50 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:53:39.45 AM" />
   <InstantaneousBeatsPerMinute bpm="66" time="12:53:40.36 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="12:53:41.33 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="12:53:42.29 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="12:53:43.31 AM" />
   <InstantaneousBeatsPerMinute bpm="55" time="12:53:44.39 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="12:53:45.34 AM" />
  </HeartRateVariabilityMetadataList>
 </Record>
 

<Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3e40&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="ms" creationDate="2025-11-18 02:37:44 -0700" startDate="2025-11-18 02:36:43 -0700" endDate="2025-11-18 02:37:38 -0700" value="61.6607">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
  <HeartRateVariabilityMetadataList>
   <InstantaneousBeatsPerMinute bpm="60" time="2:36:44.58 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="2:36:45.61 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="2:36:46.60 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:36:47.63 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:36:48.66 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="2:36:49.64 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:36:50.68 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="2:36:51.75 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:36:52.75 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:36:53.78 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="2:36:54.86 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:36:55.90 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:36:56.93 AM" />
   <InstantaneousBeatsPerMinute bpm="57" time="2:36:57.97 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:36:58.98 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:36:59.98 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="2:37:00.97 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="2:37:01.93 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="2:37:02.89 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="2:37:03.84 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="2:37:04.78 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="2:37:05.74 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="2:37:06.70 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="2:37:07.63 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="2:37:08.59 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:09.59 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="2:37:10.49 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="2:37:11.42 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="2:37:12.37 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="2:37:13.26 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="2:37:14.16 AM" />
   <InstantaneousBeatsPerMinute bpm="70" time="2:37:15.02 AM" />
   <InstantaneousBeatsPerMinute bpm="71" time="2:37:15.87 AM" />
   <InstantaneousBeatsPerMinute bpm="72" time="2:37:16.70 AM" />
   <InstantaneousBeatsPerMinute bpm="68" time="2:37:17.59 AM" />
   <InstantaneousBeatsPerMinute bpm="65" time="2:37:18.51 AM" />
   <InstantaneousBeatsPerMinute bpm="53" time="2:37:19.65 AM" />
   <InstantaneousBeatsPerMinute bpm="54" time="2:37:20.76 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="2:37:21.84 AM" />
   <InstantaneousBeatsPerMinute bpm="57" time="2:37:22.88 AM" />
   <InstantaneousBeatsPerMinute bpm="57" time="2:37:23.93 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="2:37:24.92 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:25.91 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:26.91 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="2:37:27.88 AM" />
   <InstantaneousBeatsPerMinute bpm="63" time="2:37:28.83 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:29.82 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="2:37:30.80 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:31.79 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="2:37:32.78 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="2:37:33.80 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:34.79 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="2:37:35.81 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="2:37:36.85 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="2:37:37.86 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="2:37:38.87 AM" />
  </HeartRateVariabilityMetadataList>
 </Record>
 

<Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3e40&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="ms" creationDate="2025-11-18 04:37:46 -0700" startDate="2025-11-18 04:36:45 -0700" endDate="2025-11-18 04:37:44 -0700" value="94.7018">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
  <HeartRateVariabilityMetadataList>
   <InstantaneousBeatsPerMinute bpm="52" time="4:36:46.69 AM" />
   <InstantaneousBeatsPerMinute bpm="53" time="4:36:47.81 AM" />
   <InstantaneousBeatsPerMinute bpm="49" time="4:36:49.03 AM" />
   <InstantaneousBeatsPerMinute bpm="50" time="4:36:50.22 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="4:36:51.22 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="4:36:52.21 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="4:36:53.14 AM" />
   <InstantaneousBeatsPerMinute bpm="65" time="4:36:54.06 AM" />
   <InstantaneousBeatsPerMinute bpm="65" time="4:36:54.98 AM" />
   <InstantaneousBeatsPerMinute bpm="67" time="4:36:55.88 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="4:36:56.89 AM" />
   <InstantaneousBeatsPerMinute bpm="52" time="4:36:58.05 AM" />
   <InstantaneousBeatsPerMinute bpm="52" time="4:36:59.19 AM" />
   <InstantaneousBeatsPerMinute bpm="54" time="4:37:00.31 AM" />
   <InstantaneousBeatsPerMinute bpm="52" time="4:37:01.46 AM" />
   <InstantaneousBeatsPerMinute bpm="53" time="4:37:02.60 AM" />
   <InstantaneousBeatsPerMinute bpm="53" time="4:37:03.73 AM" />
   <InstantaneousBeatsPerMinute bpm="52" time="4:37:04.88 AM" />
   <InstantaneousBeatsPerMinute bpm="54" time="4:37:05.99 AM" />
   <InstantaneousBeatsPerMinute bpm="53" time="4:37:07.13 AM" />
   <InstantaneousBeatsPerMinute bpm="50" time="4:37:08.32 AM" />
   <InstantaneousBeatsPerMinute bpm="52" time="4:37:09.48 AM" />
   <InstantaneousBeatsPerMinute bpm="50" time="4:37:10.67 AM" />
   <InstantaneousBeatsPerMinute bpm="51" time="4:37:11.85 AM" />
   <InstantaneousBeatsPerMinute bpm="51" time="4:37:13.03 AM" />
   <InstantaneousBeatsPerMinute bpm="47" time="4:37:14.29 AM" />
   <InstantaneousBeatsPerMinute bpm="49" time="4:37:15.52 AM" />
   <InstantaneousBeatsPerMinute bpm="52" time="4:37:16.68 AM" />
   <InstantaneousBeatsPerMinute bpm="50" time="4:37:17.89 AM" />
   <InstantaneousBeatsPerMinute bpm="54" time="4:37:19.00 AM" />
   <InstantaneousBeatsPerMinute bpm="49" time="4:37:20.23 AM" />
   <InstantaneousBeatsPerMinute bpm="50" time="4:37:21.44 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="4:37:22.52 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="4:37:23.59 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="4:37:24.56 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="4:37:25.56 AM" />
   <InstantaneousBeatsPerMinute bpm="65" time="4:37:26.49 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="4:37:27.55 AM" />
   <InstantaneousBeatsPerMinute bpm="55" time="4:37:28.65 AM" />
   <InstantaneousBeatsPerMinute bpm="57" time="4:37:29.71 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="4:37:30.70 AM" />
   <InstantaneousBeatsPerMinute bpm="64" time="4:37:31.64 AM" />
   <InstantaneousBeatsPerMinute bpm="62" time="4:37:32.60 AM" />
   <InstantaneousBeatsPerMinute bpm="59" time="4:37:33.62 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="4:37:34.69 AM" />
   <InstantaneousBeatsPerMinute bpm="60" time="4:37:35.69 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="4:37:36.76 AM" />
   <InstantaneousBeatsPerMinute bpm="54" time="4:37:37.88 AM" />
   <InstantaneousBeatsPerMinute bpm="61" time="4:37:38.85 AM" />
   <InstantaneousBeatsPerMinute bpm="58" time="4:37:39.90 AM" />
   <InstantaneousBeatsPerMinute bpm="53" time="4:37:41.02 AM" />
   <InstantaneousBeatsPerMinute bpm="55" time="4:37:42.10 AM" />
   <InstantaneousBeatsPerMinute bpm="56" time="4:37:43.17 AM" />
   <InstantaneousBeatsPerMinute bpm="54" time="4:37:44.29 AM" />
  </HeartRateVariabilityMetadataList>
 </Record>

<Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3e40&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="ms" creationDate="2025-11-18 08:47:01 -0700" startDate="2025-11-18 08:46:00 -0700" endDate="2025-11-18 08:47:00 -0700" value="27.8402">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
  <HeartRateVariabilityMetadataList>
   <InstantaneousBeatsPerMinute bpm="74" time="8:46:01.99 AM" />
   <InstantaneousBeatsPerMinute bpm="74" time="8:46:02.81 AM" />
   <InstantaneousBeatsPerMinute bpm="72" time="8:46:03.65 AM" />
   <InstantaneousBeatsPerMinute bpm="72" time="8:46:04.48 AM" />
   <InstantaneousBeatsPerMinute bpm="72" time="8:46:05.31 AM" />
   <InstantaneousBeatsPerMinute bpm="72" time="8:46:06.15 AM" />
   <InstantaneousBeatsPerMinute bpm="71" time="8:46:06.99 AM" />
   <InstantaneousBeatsPerMinute bpm="73" time="8:46:07.81 AM" />
   <InstantaneousBeatsPerMinute bpm="73" time="8:46:08.63 AM" />
   <InstantaneousBeatsPerMinute bpm="73" time="8:46:09.46 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:10.26 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:11.07 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:11.87 AM" />
   <InstantaneousBeatsPerMinute bpm="73" time="8:46:12.69 AM" />
   <InstantaneousBeatsPerMinute bpm="74" time="8:46:13.50 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:14.31 AM" />
   <InstantaneousBeatsPerMinute bpm="74" time="8:46:15.12 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:15.91 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:16.70 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:17.50 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:18.30 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:19.09 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:19.88 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:20.67 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:21.44 AM" />
   <InstantaneousBeatsPerMinute bpm="77" time="8:46:22.22 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:23.00 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:23.76 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:24.54 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:25.32 AM" />
   <InstantaneousBeatsPerMinute bpm="77" time="8:46:26.10 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:26.89 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="8:46:31.39 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="8:46:32.13 AM" />
   <InstantaneousBeatsPerMinute bpm="82" time="8:46:32.87 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:33.64 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:34.43 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:35.23 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:36.02 AM" />
   <InstantaneousBeatsPerMinute bpm="74" time="8:46:36.82 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:37.61 AM" />
   <InstantaneousBeatsPerMinute bpm="77" time="8:46:38.39 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:39.15 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:39.92 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="8:46:40.67 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="8:46:41.42 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="8:46:42.17 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="8:46:42.90 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:51.19 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:51.99 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:46:52.78 AM" />
   <InstantaneousBeatsPerMinute bpm="74" time="8:46:53.60 AM" />
   <InstantaneousBeatsPerMinute bpm="73" time="8:46:54.42 AM" />
   <InstantaneousBeatsPerMinute bpm="75" time="8:46:55.22 AM" />
   <InstantaneousBeatsPerMinute bpm="77" time="8:46:56.00 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:56.77 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="8:46:57.54 AM" />
   <InstantaneousBeatsPerMinute bpm="79" time="8:46:58.30 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="8:46:59.04 AM" />
   <InstantaneousBeatsPerMinute bpm="79" time="8:46:59.80 AM" />
   <InstantaneousBeatsPerMinute bpm="76" time="8:47:00.59 AM" />
  </HeartRateVariabilityMetadataList>
 </Record>
 

<Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3e40&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="ms" creationDate="2025-11-18 11:15:16 -0700" startDate="2025-11-18 11:14:14 -0700" endDate="2025-11-18 11:15:12 -0700" value="26.4928">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
  <HeartRateVariabilityMetadataList>
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:15.97 AM" />
   <InstantaneousBeatsPerMinute bpm="87" time="11:14:19.49 AM" />
   <InstantaneousBeatsPerMinute bpm="89" time="11:14:20.16 AM" />
   <InstantaneousBeatsPerMinute bpm="89" time="11:14:20.84 AM" />
   <InstantaneousBeatsPerMinute bpm="86" time="11:14:21.53 AM" />
   <InstantaneousBeatsPerMinute bpm="85" time="11:14:22.23 AM" />
   <InstantaneousBeatsPerMinute bpm="85" time="11:14:26.56 AM" />
   <InstantaneousBeatsPerMinute bpm="85" time="11:14:27.27 AM" />
   <InstantaneousBeatsPerMinute bpm="85" time="11:14:27.97 AM" />
   <InstantaneousBeatsPerMinute bpm="85" time="11:14:28.68 AM" />
   <InstantaneousBeatsPerMinute bpm="84" time="11:14:29.39 AM" />
   <InstantaneousBeatsPerMinute bpm="84" time="11:14:30.10 AM" />
   <InstantaneousBeatsPerMinute bpm="84" time="11:14:30.81 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:31.54 AM" />
   <InstantaneousBeatsPerMinute bpm="82" time="11:14:32.27 AM" />
   <InstantaneousBeatsPerMinute bpm="84" time="11:14:32.98 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:33.71 AM" />
   <InstantaneousBeatsPerMinute bpm="82" time="11:14:34.44 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:35.17 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:35.89 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="11:14:36.63 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="11:14:37.38 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="11:14:38.12 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="11:14:38.86 AM" />
   <InstantaneousBeatsPerMinute bpm="79" time="11:14:39.62 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="11:14:40.37 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:41.10 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:14:41.82 AM" />
   <InstantaneousBeatsPerMinute bpm="82" time="11:14:42.55 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="11:14:43.30 AM" />
   <InstantaneousBeatsPerMinute bpm="79" time="11:14:44.06 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="11:14:44.83 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="11:14:45.59 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="11:14:46.36 AM" />
   <InstantaneousBeatsPerMinute bpm="77" time="11:14:47.15 AM" />
   <InstantaneousBeatsPerMinute bpm="78" time="11:14:47.91 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="11:14:48.66 AM" />
   <InstantaneousBeatsPerMinute bpm="85" time="11:14:49.37 AM" />
   <InstantaneousBeatsPerMinute bpm="82" time="11:14:50.10 AM" />
   <InstantaneousBeatsPerMinute bpm="84" time="11:14:50.82 AM" />
   <InstantaneousBeatsPerMinute bpm="80" time="11:14:51.56 AM" />
   <InstantaneousBeatsPerMinute bpm="89" time="11:15:09.07 AM" />
   <InstantaneousBeatsPerMinute bpm="87" time="11:15:11.15 AM" />
   <InstantaneousBeatsPerMinute bpm="83" time="11:15:11.87 AM" />
   <InstantaneousBeatsPerMinute bpm="81" time="11:15:12.61 AM" />
  </HeartRateVariabilityMetadataList>
 </Record>
 

<Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3e40&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="ms" creationDate="2025-11-18 12:41:23 -0700" startDate="2025-11-18 12:40:22 -0700" endDate="2025-11-18 12:41:20 -0700" value="50.1529">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
  <HeartRateVariabilityMetadataList>
   <InstantaneousBeatsPerMinute bpm="77" time="12:40:36.58 PM" />
   <InstantaneousBeatsPerMinute bpm="75" time="12:40:37.38 PM" />
   <InstantaneousBeatsPerMinute bpm="72" time="12:40:38.22 PM" />
   <InstantaneousBeatsPerMinute bpm="76" time="12:40:47.47 PM" />
   <InstantaneousBeatsPerMinute bpm="76" time="12:40:48.27 PM" />
   <InstantaneousBeatsPerMinute bpm="68" time="12:40:49.15 PM" />
   <InstantaneousBeatsPerMinute bpm="66" time="12:40:50.05 PM" />
   <InstantaneousBeatsPerMinute bpm="69" time="12:40:50.93 PM" />
   <InstantaneousBeatsPerMinute bpm="70" time="12:40:51.79 PM" />
   <InstantaneousBeatsPerMinute bpm="71" time="12:40:52.64 PM" />
   <InstantaneousBeatsPerMinute bpm="72" time="12:40:53.47 PM" />