<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 14 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord|Audiogram|VisionPrescription)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth                   CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex                 CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType                     CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse   CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute|WorkoutStatistics)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutActivity ((MetadataEntry)*)>
<!ATTLIST WorkoutActivity
  uuid                 CDATA #REQUIRED
  startDate            CDATA #REQUIRED
  endDate              CDATA #IMPLIED
  duration             CDATA #IMPLIED
  durationUnit         CDATA #IMPLIED
>
<!ELEMENT WorkoutEvent ((MetadataEntry)*)>
<!ATTLIST WorkoutEvent
  type                 CDATA #REQUIRED
  date                 CDATA #REQUIRED
  duration             CDATA #IMPLIED
  durationUnit         CDATA #IMPLIED
>
<!ELEMENT WorkoutStatistics EMPTY>
<!ATTLIST WorkoutStatistics
  type                 CDATA #REQUIRED
  startDate            CDATA #REQUIRED
  endDate              CDATA #REQUIRED
  average              CDATA #IMPLIED
  minimum              CDATA #IMPLIED
  maximum              CDATA #IMPLIED
  sum                  CDATA #IMPLIED
  unit                 CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram ((MetadataEntry|SensitivityPoint)*)>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  leftEarMasked      CDATA #IMPLIED
  leftEarClampingRangeLowerBound   CDATA #IMPLIED
  leftEarClampingRangeUpperBound   CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
  rightEarMasked      CDATA #IMPLIED
  rightEarClampingRangeLowerBound  CDATA #IMPLIED
  rightEarClampingRangeUpperBound  CDATA #IMPLIED
>
<!ELEMENT VisionPrescription ((RightEye|LeftEye|Attachment|MetadataEntry)*)>
<!ATTLIST VisionPrescription
  type             CDATA #REQUIRED
  dateIssued       CDATA #REQUIRED
  expirationDate   CDATA #IMPLIED
  brand            CDATA #IMPLIED
>
<!ELEMENT RightEye EMPTY>
<!ATTLIST RightEye
  sphere           CDATA #IMPLIED
  sphereUnit       CDATA #IMPLIED
  cylinder         CDATA #IMPLIED
  cylinderUnit     CDATA #IMPLIED
  axis             CDATA #IMPLIED
  axisUnit         CDATA #IMPLIED
  add              CDATA #IMPLIED
  addUnit          CDATA #IMPLIED
  vertex           CDATA #IMPLIED
  vertexUnit       CDATA #IMPLIED
  prismAmount      CDATA #IMPLIED
  prismAmountUnit  CDATA #IMPLIED
  prismAngle       CDATA #IMPLIED
  prismAngleUnit   CDATA #IMPLIED
  farPD            CDATA #IMPLIED
  farPDUnit        CDATA #IMPLIED
  nearPD           CDATA #IMPLIED
  nearPDUnit       CDATA #IMPLIED
  baseCurve        CDATA #IMPLIED
  baseCurveUnit    CDATA #IMPLIED
  diameter         CDATA #IMPLIED
  diameterUnit     CDATA #IMPLIED
>
<!ELEMENT LeftEye EMPTY>
<!ATTLIST LeftEye
  sphere           CDATA #IMPLIED
  sphereUnit       CDATA #IMPLIED
  cylinder         CDATA #IMPLIED
  cylinderUnit     CDATA #IMPLIED
  axis             CDATA #IMPLIED
  axisUnit         CDATA #IMPLIED
  add              CDATA #IMPLIED
  addUnit          CDATA #IMPLIED
  vertex           CDATA #IMPLIED
  vertexUnit       CDATA #IMPLIED
  prismAmount      CDATA #IMPLIED
  prismAmountUnit  CDATA #IMPLIED
  prismAngle       CDATA #IMPLIED
  prismAngleUnit   CDATA #IMPLIED
  farPD            CDATA #IMPLIED
  farPDUnit        CDATA #IMPLIED
  nearPD           CDATA #IMPLIED
  nearPDUnit       CDATA #IMPLIED
  baseCurve        CDATA #IMPLIED
  baseCurveUnit    CDATA #IMPLIED
  diameter         CDATA #IMPLIED
  diameterUnit     CDATA #IMPLIED
>
<!ELEMENT Attachment EMPTY>
<!ATTLIST Attachment
  identifier       CDATA #IMPLIED
>
]>
<HealthData locale="en_US">

<ExportDate value="2025-12-18 06:18:45 -0700" />
 

<Me HKCharacteristicTypeIdentifierDateOfBirth="1981-05-22" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="None" />
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 01:34:27 -0700" startDate="2025-11-18 01:34:27 -0700" endDate="2025-11-18 01:34:27 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.048 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 02:44:51 -0700" startDate="2025-11-18 02:44:50 -0700" endDate="2025-11-18 02:44:50 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0691 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 04:31:49 -0700" startDate="2025-11-18 04:31:48 -0700" endDate="2025-11-18 04:31:48 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0745 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 05:01:49 -0700" startDate="2025-11-18 05:01:49 -0700" endDate="2025-11-18 05:01:49 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0706 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 06:19:50 -0700" startDate="2025-11-18 06:19:50 -0700" endDate="2025-11-18 06:19:50 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0732 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 08:02:31 -0700" startDate="2025-11-18 08:02:31 -0700" endDate="2025-11-18 08:02:31 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.8253 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c2d00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 09:14:23 -0700" startDate="2025-11-18 09:14:31 -0700" endDate="2025-11-18 09:14:31 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.8415 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c1680&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 13:30:38 -0700" startDate="2025-11-18 13:30:38 -0700" endDate="2025-11-18 13:30:38 -0700" value="0.93">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.6944 kPa" />
 </Record>
<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 20:43:47 -0700" startDate="2025-11-18 20:43:47 -0700" endDate="2025-11-18 20:43:47 -0700" value="0.93">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9861 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 21:13:48 -0700" startDate="2025-11-18 21:13:47 -0700" endDate="2025-11-18 21:13:47 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0209 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 21:43:44 -0700" startDate="2025-11-18 21:43:48 -0700" endDate="2025-11-18 21:43:48 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0542 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-18 22:20:52 -0700" startDate="2025-11-18 22:20:51 -0700" endDate="2025-11-18 22:20:51 -0700" value="0.9">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0581 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-19 04:27:00 -0700" startDate="2025-11-19 04:27:00 -0700" endDate="2025-11-19 04:27:00 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0969 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-19 05:19:14 -0700" startDate="2025-11-19 05:19:13 -0700" endDate="2025-11-19 05:19:13 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.1106 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-19 06:23:08 -0700" startDate="2025-11-19 06:23:07 -0700" endDate="2025-11-19 06:23:07 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.094 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-19 08:05:06 -0700" startDate="2025-11-19 08:05:05 -0700" endDate="2025-11-19 08:05:05 -0700" value="0.93">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9021 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-19 09:05:06 -0700" startDate="2025-11-19 09:05:06 -0700" endDate="2025-11-19 09:05:06 -0700" value="0.93">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9985 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="11.6.1" device="&lt;&lt;HKDevice: 0x7d82c3c00&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:11.6.1, creation date:2025-08-28 15:48:28 +0000&gt;" unit="%" creationDate="2025-11-19 09:40:32 -0700" startDate="2025-11-19 09:40:39 -0700" endDate="2025-11-19 09:40:39 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0181 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 14:11:01 -0700" startDate="2025-11-19 14:11:00 -0700" endDate="2025-11-19 14:11:00 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.8131 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 15:15:05 -0700" startDate="2025-11-19 15:15:04 -0700" endDate="2025-11-19 15:15:04 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.752 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 15:48:32 -0700" startDate="2025-11-19 15:48:31 -0700" endDate="2025-11-19 15:48:31 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.7472 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 16:19:23 -0700" startDate="2025-11-19 16:19:22 -0700" endDate="2025-11-19 16:19:22 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.7296 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 17:39:42 -0700" startDate="2025-11-19 17:39:41 -0700" endDate="2025-11-19 17:39:41 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9819 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 18:42:44 -0700" startDate="2025-11-19 18:42:42 -0700" endDate="2025-11-19 18:42:42 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9894 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 19:12:44 -0700" startDate="2025-11-19 19:12:43 -0700" endDate="2025-11-19 19:12:43 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9986 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 20:39:58 -0700" startDate="2025-11-19 20:39:57 -0700" endDate="2025-11-19 20:39:57 -0700" value="0.93">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9987 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-19 21:56:01 -0700" startDate="2025-11-19 21:56:00 -0700" endDate="2025-11-19 21:56:00 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.6721 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 04:07:19 -0700" startDate="2025-11-20 04:07:19 -0700" endDate="2025-11-20 04:07:19 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.8955 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 04:41:49 -0700" startDate="2025-11-20 04:41:49 -0700" endDate="2025-11-20 04:41:49 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.878 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 05:19:31 -0700" startDate="2025-11-20 05:19:30 -0700" endDate="2025-11-20 05:19:30 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.8699 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 05:55:37 -0700" startDate="2025-11-20 05:55:36 -0700" endDate="2025-11-20 05:55:36 -0700" value="0.97">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.851 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 06:25:37 -0700" startDate="2025-11-20 06:25:36 -0700" endDate="2025-11-20 06:25:36 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.8381 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 08:07:34 -0700" startDate="2025-11-20 08:07:40 -0700" endDate="2025-11-20 08:07:40 -0700" value="0.93">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.6275 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 09:46:11 -0700" startDate="2025-11-20 09:46:09 -0700" endDate="2025-11-20 09:46:09 -0700" value="0.94">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.663 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 13:54:55 -0700" startDate="2025-11-20 13:55:02 -0700" endDate="2025-11-20 13:55:02 -0700" value="0.97">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.5114 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 14:55:57 -0700" startDate="2025-11-20 14:55:59 -0700" endDate="2025-11-20 14:55:59 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.5109 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 19:33:43 -0700" startDate="2025-11-20 19:33:41 -0700" endDate="2025-11-20 19:33:41 -0700" value="0.92">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9233 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 20:50:28 -0700" startDate="2025-11-20 20:50:33 -0700" endDate="2025-11-20 20:50:33 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="85.9446 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 21:50:34 -0700" startDate="2025-11-20 21:50:33 -0700" endDate="2025-11-20 21:50:33 -0700" value="0.97">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.004 kPa" />
 </Record>
<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 22:21:12 -0700" startDate="2025-11-20 22:21:11 -0700" endDate="2025-11-20 22:21:11 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0137 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 22:53:53 -0700" startDate="2025-11-20 22:54:00 -0700" endDate="2025-11-20 22:54:00 -0700" value="0.96">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0449 kPa" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierOxygenSaturation" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c1c80&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="%" creationDate="2025-11-20 23:24:02 -0700" startDate="2025-11-20 23:24:00 -0700" endDate="2025-11-20 23:24:00 -0700" value="0.95">
  <MetadataEntry key="HKMetadataKeyBarometricPressure" value="86.0727 kPa" />
 </Record>
 
