<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 14 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord|Audiogram|VisionPrescription)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth                   CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex                 CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType                     CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse   CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute|WorkoutStatistics)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutActivity ((MetadataEntry)*)>
<!ATTLIST WorkoutActivity
  uuid                 CDATA #REQUIRED
  startDate            CDATA #REQUIRED
  endDate              CDATA #IMPLIED
  duration             CDATA #IMPLIED
  durationUnit         CDATA #IMPLIED
>
<!ELEMENT WorkoutEvent ((MetadataEntry)*)>
<!ATTLIST WorkoutEvent
  type                 CDATA #REQUIRED
  date                 CDATA #REQUIRED
  duration             CDATA #IMPLIED
  durationUnit         CDATA #IMPLIED
>
<!ELEMENT WorkoutStatistics EMPTY>
<!ATTLIST WorkoutStatistics
  type                 CDATA #REQUIRED
  startDate            CDATA #REQUIRED
  endDate              CDATA #REQUIRED
  average              CDATA #IMPLIED
  minimum              CDATA #IMPLIED
  maximum              CDATA #IMPLIED
  sum                  CDATA #IMPLIED
  unit                 CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram ((MetadataEntry|SensitivityPoint)*)>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  leftEarMasked      CDATA #IMPLIED
  leftEarClampingRangeLowerBound   CDATA #IMPLIED
  leftEarClampingRangeUpperBound   CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
  rightEarMasked      CDATA #IMPLIED
  rightEarClampingRangeLowerBound  CDATA #IMPLIED
  rightEarClampingRangeUpperBound  CDATA #IMPLIED
>
<!ELEMENT VisionPrescription ((RightEye|LeftEye|Attachment|MetadataEntry)*)>
<!ATTLIST VisionPrescription
  type             CDATA #REQUIRED
  dateIssued       CDATA #REQUIRED
  expirationDate   CDATA #IMPLIED
  brand            CDATA #IMPLIED
>
<!ELEMENT RightEye EMPTY>
<!ATTLIST RightEye
  sphere           CDATA #IMPLIED
  sphereUnit       CDATA #IMPLIED
  cylinder         CDATA #IMPLIED
  cylinderUnit     CDATA #IMPLIED
  axis             CDATA #IMPLIED
  axisUnit         CDATA #IMPLIED
  add              CDATA #IMPLIED
  addUnit          CDATA #IMPLIED
  vertex           CDATA #IMPLIED
  vertexUnit       CDATA #IMPLIED
  prismAmount      CDATA #IMPLIED
  prismAmountUnit  CDATA #IMPLIED
  prismAngle       CDATA #IMPLIED
  prismAngleUnit   CDATA #IMPLIED
  farPD            CDATA #IMPLIED
  farPDUnit        CDATA #IMPLIED
  nearPD           CDATA #IMPLIED
  nearPDUnit       CDATA #IMPLIED
  baseCurve        CDATA #IMPLIED
  baseCurveUnit    CDATA #IMPLIED
  diameter         CDATA #IMPLIED
  diameterUnit     CDATA #IMPLIED
>
<!ELEMENT LeftEye EMPTY>
<!ATTLIST LeftEye
  sphere           CDATA #IMPLIED
  sphereUnit       CDATA #IMPLIED
  cylinder         CDATA #IMPLIED
  cylinderUnit     CDATA #IMPLIED
  axis             CDATA #IMPLIED
  axisUnit         CDATA #IMPLIED
  add              CDATA #IMPLIED
  addUnit          CDATA #IMPLIED
  vertex           CDATA #IMPLIED
  vertexUnit       CDATA #IMPLIED
  prismAmount      CDATA #IMPLIED
  prismAmountUnit  CDATA #IMPLIED
  prismAngle       CDATA #IMPLIED
  prismAngleUnit   CDATA #IMPLIED
  farPD            CDATA #IMPLIED
  farPDUnit        CDATA #IMPLIED
  nearPD           CDATA #IMPLIED
  nearPDUnit       CDATA #IMPLIED
  baseCurve        CDATA #IMPLIED
  baseCurveUnit    CDATA #IMPLIED
  diameter         CDATA #IMPLIED
  diameterUnit     CDATA #IMPLIED
>
<!ELEMENT Attachment EMPTY>
<!ATTLIST Attachment
  identifier       CDATA #IMPLIED
>
]>
<HealthData locale="en_US">

<ExportDate value="2025-12-18 06:18:45 -0700" />
 

<Me HKCharacteristicTypeIdentifierDateOfBirth="1981-05-22" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="None" />
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-11-21 06:45:07 -0700" startDate="2025-11-20 22:56:39 -0700" endDate="2025-11-21 06:45:05 -0700" value="95.074">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-11-23 07:00:07 -0700" startDate="2025-11-23 00:05:42 -0700" endDate="2025-11-23 07:00:05 -0700" value="95.6679">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-11-24 07:06:45 -0700" startDate="2025-11-23 21:52:05 -0700" endDate="2025-11-24 07:06:41 -0700" value="94.662">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-11-25 06:45:09 -0700" startDate="2025-11-25 00:00:01 -0700" endDate="2025-11-25 06:45:05 -0700" value="95.1833">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-11-26 06:54:39 -0700" startDate="2025-11-26 00:00:01 -0700" endDate="2025-11-26 06:54:35 -0700" value="94.0248">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-11-30 06:30:16 -0700" startDate="2025-11-30 00:00:01 -0700" endDate="2025-11-30 06:30:14 -0700" value="95.0787">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-01 06:45:03 -0700" startDate="2025-12-01 00:00:01 -0700" endDate="2025-12-01 06:45:02 -0700" value="95.5686">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-02 06:47:50 -0700" startDate="2025-12-02 00:00:01 -0700" endDate="2025-12-02 06:47:49 -0700" value="95.8442">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-05 06:00:07 -0700" startDate="2025-12-04 21:54:37 -0700" endDate="2025-12-05 06:00:04 -0700" value="95.2608">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-06 06:45:22 -0700" startDate="2025-12-05 23:45:42 -0700" endDate="2025-12-06 06:45:21 -0700" value="94.8577">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-07 06:00:22 -0700" startDate="2025-12-07 00:00:00 -0700" endDate="2025-12-07 06:00:20 -0700" value="95.0197">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-08 06:00:14 -0700" startDate="2025-12-08 00:00:00 -0700" endDate="2025-12-08 06:00:12 -0700" value="95.2013">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-10 06:09:31 -0700" startDate="2025-12-09 22:33:02 -0700" endDate="2025-12-10 06:09:29 -0700" value="95.0266">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-12 06:00:18 -0700" startDate="2025-12-12 00:00:01 -0700" endDate="2025-12-12 06:00:17 -0700" value="94.926">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-14 06:35:07 -0700" startDate="2025-12-14 00:15:57 -0700" endDate="2025-12-14 06:35:04 -0700" value="94.2855">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-15 06:00:09 -0700" startDate="2025-12-15 00:00:01 -0700" endDate="2025-12-15 06:00:07 -0700" value="94.7511">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-16 06:09:34 -0700" startDate="2025-12-16 00:00:01 -0700" endDate="2025-12-16 06:09:33 -0700" value="95.3323">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-17 06:02:45 -0700" startDate="2025-12-17 00:00:02 -0700" endDate="2025-12-17 06:00:10 -0700" value="95.4365">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
 

<Record type="HKQuantityTypeIdentifierAppleSleepingWristTemperature" sourceName="Carl’s Apple Watch" sourceVersion="26.1" device="&lt;&lt;HKDevice: 0x7d82c08a0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,18, software:26.1, creation date:2025-11-19 20:32:00 +0000&gt;" unit="degF" creationDate="2025-12-18 06:00:19 -0700" startDate="2025-12-18 00:00:01 -0700" endDate="2025-12-18 06:00:18 -0700" value="94.6885">
  <MetadataEntry key="HKAlgorithmVersion" value="2" />
 </Record>
<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-08 22:31:29 -0700" endDate="2025-11-09 01:31:29 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 01:49:59 -0700" endDate="2025-11-09 02:08:59 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 02:11:29 -0700" endDate="2025-11-09 03:07:59 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 03:08:29 -0700" endDate="2025-11-09 04:35:59 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 04:37:29 -0700" endDate="2025-11-09 06:15:29 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 06:16:29 -0700" endDate="2025-11-09 06:23:59 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-08 22:31:29 -0700" endDate="2025-11-09 06:23:59 -0700" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 23:02:02 -0700" endDate="2025-11-09 23:06:32 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 23:11:02 -0700" endDate="2025-11-10 02:03:32 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 02:04:02 -0700" endDate="2025-11-10 02:58:32 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 03:04:02 -0700" endDate="2025-11-10 03:09:02 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 03:10:02 -0700" endDate="2025-11-10 04:03:32 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 04:20:32 -0700" endDate="2025-11-10 04:50:32 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 04:51:02 -0700" endDate="2025-11-10 06:38:02 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 06:44:02 -0700" endDate="2025-11-10 06:45:02 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-09 23:02:02 -0700" endDate="2025-11-10 06:45:02 -0700" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-10 22:14:13 -0700" endDate="2025-11-10 23:03:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-10 22:14:13 -0700" endDate="2025-11-10 23:03:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 22:14:13 -0700" endDate="2025-11-10 23:03:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-10 23:04:13 -0700" endDate="2025-11-11 00:58:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-10 23:04:13 -0700" endDate="2025-11-11 00:58:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-10 23:04:13 -0700" endDate="2025-11-11 00:58:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-11 00:59:13 -0700" endDate="2025-11-11 02:37:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-11 00:59:13 -0700" endDate="2025-11-11 02:37:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-11 00:59:13 -0700" endDate="2025-11-11 02:37:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-11 02:38:43 -0700" endDate="2025-11-11 03:29:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-11 02:38:43 -0700" endDate="2025-11-11 03:29:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-11 02:38:43 -0700" endDate="2025-11-11 03:29:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-11 03:29:43 -0700" endDate="2025-11-11 03:53:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-11 03:29:43 -0700" endDate="2025-11-11 03:53:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-11 03:29:43 -0700" endDate="2025-11-11 03:53:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-11 04:14:43 -0700" endDate="2025-11-11 04:29:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-11 04:14:43 -0700" endDate="2025-11-11 04:29:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-21 09:10:13 -0700" startDate="2025-11-11 04:14:43 -0700" endDate="2025-11-11 04:29:43 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-11 04:30:13 -0700" endDate="2025-11-11 05:23:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 13:56:03 -0700" startDate="2025-11-10 22:14:13 -0700" endDate="2025-11-11 05:23:13 -0700" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="HKTimeZone" value="America/Denver" />
 </Record>
 

<Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Sleep++" sourceVersion="130" creationDate="2025-11-20 21:31:30 -0700" startDate="2025-11-11 04:30:13 -0700" endDate="2025-11-11 05:23:13 -0700" value="HKCategoryValueSleepAnalysisAsleepUnspecified">